import mongoose from "mongoose";

/**
 * Source:
 *   "ai"          — generated by Gemini
 *   "interviewer" — typed by human interviewer in peer mode
 *
 * Type:
 *   "opening"  — first question of the session
 *   "followup" — contextual follow-up based on previous answer
 *   "closing"  — wrap-up question
 */
const questionSchema = new mongoose.Schema(
  {
    session: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "InterviewSession",
      required: true,
      index: true,
    },
    sequence: {
      type: Number,
      required: true, // 1-based order within the session
    },
    text: {
      type: String,
      required: true,
    },
    source: {
      type: String,
      enum: ["ai", "interviewer"],
      default: "ai",
    },
    type: {
      type: String,
      enum: ["opening", "followup", "closing"],
      default: "followup",
    },
    topic: {
      type: String, // sub-topic tag e.g. "recursion", "system design"
      default: "",
    },
  },
  { timestamps: true }
);

const Question = mongoose.model("Question", questionSchema);
export default Question;
